#!/bin/bash

docker stop tomcatxerial

mvn clean package || exit 1

# other images https://hub.docker.com/_/tomcat
docker run -d --rm --name tomcatxerial tomcat:11.0.6

docker cp target/TestXerialSqliteTomcat.war tomcatxerial:/usr/local/tomcat/webapps/

docker logs -f tomcatxerial